apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: monitoring
data:
  filebeat.yml: |-
    filebeat.inputs:
    - type: container
      paths:
        - /var/lib/docker/containers/*/*.log

    output.elasticsearch:
     hosts: ["http://elasticsearch-clusterip.monitoring.svc.cluster.local:9200"]


    setup.kibana:
      host: "http://kibana.monitoring.svc.cluster.local:5601"
