# alert-rules.yaml
groups:
  - name: app-alerts
    rules:
      - alert: HighCPUUsage
        expr: sum(rate(container_cpu_usage_seconds_total{namespace="default", pod="face-recognition"}[5m])) by (pod) > 0.8
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "CPU usage is high for pod {{ $labels.pod }}"
