apiVersion: v1
kind: Pod
metadata:
  name: copy-models
  namespace: face-recognition
spec:
  containers:
  - name: copy-models
    image: busybox
    command: ["/bin/sh", "-c", "sleep 3600"]
    volumeMounts:
    - name: models-volume
      mountPath: /app/models
  volumes:
  - name: models-volume
    persistentVolumeClaim:
      claimName: models-pvc