apiVersion: v1
kind: Pod
metadata:
  name: copy-data
  namespace: face-recognition
spec:
  containers:
  - name: copy-data
    image: busybox
    command: ["/bin/sh", "-c", "sleep 3600"]
    volumeMounts:
    - name: data-volume
      mountPath: /app/
  volumes:
  - name: data-volume
    persistentVolumeClaim:
      claimName: data-pvc