# monitoring-values.yaml
prometheus:
  service:
    type: NodePort
    nodePort: 30090

grafana:
  service:
    type: NodePort
    nodePort: 30080
  adminPassword: 'admin'
  ingress:
    enabled: true
    hosts:
      - grafana.local
