apiVersion: v1
kind: Service
metadata:
  name: recognition
  namespace: face-recognition
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "5002"
    prometheus.io/path: "/metrics"

spec:
  selector:
    app: recognition
  ports:
  - port: 5002
    targetPort: 5002
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: face-recognition
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "5002"
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - port: 5002
    targetPort: 5002
    nodePort: 30003
---
apiVersion: v1
kind: Service
metadata:
  name: training
  namespace: face-recognition
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "5002"
spec:
  selector:
    app: training
  type: ClusterIP
  ports:
  - port: 5002
    targetPort: 5002
