apiVersion: apps/v1
kind: Deployment
metadata:
  name: training
  namespace: face-recognition
spec:
  replicas: 1
  selector:
    matchLabels:
      app: training
  template:
    metadata:
      labels:
        app: training
    spec:
      initContainers:
      - name: init-data
        image: busybox:latest
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c", "mkdir -p /app/data && ls -l /app/data"]
        volumeMounts:
        - name: data-volume
          mountPath: /app/data

      containers:
      - name: training
        image: aayushi6402/training:latest
        imagePullPolicy: IfNotPresent
        command: ["python"]
        args: ["train_service.py"]
        ports:
        - containerPort: 8000
          name: prom-metrics
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
        - name: mlruns-volume
          mountPath: /app/mlruns
        - name: models-volume
          mountPath: /app/models
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
          requests:
            memory: "512Mi"
            cpu: "250m"

      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: data-pvc
      - name: mlruns-volume
        persistentVolumeClaim:  
          claimName: mlruns-pvc
      - name: models-volume
        persistentVolumeClaim:
          claimName: models-pvc
